apiVersion: allocation.agones.dev/v1
kind: GameServerAllocation
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: lab-game-server
  metadata:
    annotations:
      quilkin.dev/tokens: azd4   # base64("k7x")
