apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nakama-lab-gameserverallocation-create
  namespace: default
  labels:
    app.kubernetes.io/part-of: sprint5-day8
rules:
  - apiGroups: [allocation.agones.dev]
    resources: [gameserverallocations]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nakama-lab-gameserverallocation-create
  namespace: default
  labels:
    app.kubernetes.io/part-of: sprint5-day8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nakama-lab-gameserverallocation-create
subjects:
  - kind: ServiceAccount
    name: nakama
    namespace: nakama-lab
